routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::middleware('auth')
    ->prefix('admin')
    ->name('admin.')
    ->namespace('App\Http\Controllers\Admin')
    ->group(function (){
        Route::get('/', function () {return view('admin.layouts.dashboard');})->name('dashboard');

        Route::resource('products', 'ProductController');
        Route::resource('categories', 'CategoryController');
        Route::resource('users', 'UserController')->except(['show']);
        Route::resource('messages', 'MessageController')->except(['edit', 'update', 'store']);
    });

Route::prefix('/')
    ->namespace('App\Http\Controllers\Frontend')
    ->group(function (){
        Route::get('/', 'HomeController@home')->name('home');
        Route::resource('products', 'ProductController')->only(['index', 'show']);
        Route::resource('categories', 'CategoryController')->only(['index', 'show']);
        Route::get('about', 'HomeController@about')->name('about');
        Route::get('contact', 'HomeController@contact')->name('contact');
        Route::post('contact', 'HomeController@storeMessage')->name('storeMessage');
    });


require __DIR__.'/auth.php';

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    protected $fillable = [
        'image',
        'title',
        'price',
        'description',
        'category_id',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'updated_at' => 'datetime',
        'created_at' => 'datetime',
    ];

    public function getImageUrlAttribute()
    {
        return url('storage/' . $this->image);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::orderBy('id', 'desc')->paginate(15);
        return view('admin.products.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('admin.products.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required|string',
            'price' => 'required|numeric',
            'description' => 'required|string',
            'category_id' => 'required',
            'image' => 'required|mimes:jpeg,jpg,png',
        ]);

        $imageName = time().'.'.$request->image->extension();
        $request->image->move(storage_path('app/public/images'), $imageName);

        Product::create([
            'image' => $imageName,
            'title' => $request->title,
            'price' => $request->price,
            'description' => $request->description,
            'category_id' => $request->category_id,
        ]);

        return redirect('/admin/products');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        return view('admin.products.show', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        $categories = Category::all();
        return view('admin.products.edit', compact('product', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        $request->validate([
            'title' => 'required',
            'description' => 'required',
            'category_id' => 'required',
            'image' => 'nullable',
        ]);
        if ($request->hasFile('image')){
            Storage::delete('app/public/images/' . $product->image);
            $imageName = time().'.'.$request->image->extension();
            $request->image->move(storage_path('app/public/images'), $imageName);
            $request->image = $imageName;
        };

        $product->update([
            'image' => $imageName ?? $product->image,
            'title' => $request->title,
            'description' => $request->description,
        ]);
        return redirect()->route('admin.products.show', $product->id)->with('success', 'Product updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Product::find($id)->delete();
        return redirect()->back()->with('success','Product deleted success');
    }
}

app/Http/Controllers/Frontend/ProductController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Product;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View|Response
     */
    public function index(Request $request)
    {
        $query = Product::query();

        if ($request->search_query) {
            $query->where('title', 'LIKE', '%' . $request->search_query . '%');
        }

        if ($request->category) {
            $query->where('category_id', $request->category);
        }

        $products = $query->latest()->paginate(9);
        $categories = Category::all();

        return view('frontend.products.index', compact('products', 'categories'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return Response
     */
    public function show(Product $product)
    {
        $products = $product->category->products()->take(8)->get();

        return view('frontend.products.show', compact('product', 'products'));
    }

}

resources/views/admin/products/create.blade.php
@extends('admin.layouts.master')
@section('content')
    <div class="content-wrapper" style="min-height: 1342.88px;">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Create Product</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Home</a></li>
                            <li class="breadcrumb-item active">Create Product</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <!-- left column -->
                    <div class="col-md-12">
                        <!-- general form elements -->
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        <div class="card card-primary">
                            <div class="card-header">
                                <h3 class="card-title">Create Form</h3>
                            </div>
                            <!-- /.card-header -->
                            <!-- form start -->
                            <form method="post" action="{{ route('admin.products.store') }}" enctype="multipart/form-data">
                                @csrf
                                <div class="card-body">
                                    <div class="form-group">
                                        <label for="title">
                                            Title
                                        </label>
                                        <input type="text"
                                               class="form-control"
                                               id="title"
                                               name="title"
                                               placeholder="Enter Title"
                                               value="{{ old('title') }}"
                                               required
                                               >
                                    </div>
                                    <div class="form-group">
                                        <label for="price">
                                            Price
                                        </label>
                                        <input type="text"
                                               class="form-control"
                                               name="price"
                                               placeholder="Enter Price"
                                               value="{{ old('price') }}"
                                               required
                                               >
                                    </div>
                                    <div class="form-group">
                                        <label for="description">
                                            Description
                                        </label>
                                        <textarea
                                               class="form-control"
                                               id="description"
                                               name="description"
                                               placeholder="Enter Description"
                                               required
                                               rows="10"
                                        >{{ old('description') }}</textarea>
                                      </div>
                                    <div class="form-group">
                                    <label for="inputStatus">Categories</label>
                                        <select id="inputStatus" name="category_id" class="form-control custom-select">
                                          <option selected disabled>Select one</option>
                                           @foreach($categories as $category)
                                                <option value="{{ $category->id }}"> {{ $category->name }} </option>
                                           @endforeach

                                        </select>
                                    </div>

                                    <div class="form-group">
                                        <label for="image">
                                            Photo
                                        </label>
                                        <div class="input-group">
                                            <div class="custom-file">
                                                <input type="file"
                                                       class="custom-file-input"
                                                       id="image"
                                                       name="image"
                                                       required
                                                       >
                                                <label class="custom-file-label"
                                                       for="productImage">
                                                    Choose Image
                                                </label>
                                            </div>

                                            <div class="input-group-append">
                                                <span class="input-group-text">
                                                    Upload
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- /.card-body -->

                                <div class="card-footer">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </div>
                            </form>
                        </div>
                        <!-- /.card -->
                    </div>
                    <!--/.col (left) -->
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
@endsection

resources/views/admin/products/edit.blade.php
@extends('admin.layouts.master')
@section('content')
    <div class="content-wrapper" style="min-height: 1342.88px;">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Edit Product</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Home</a></li>
                            <li class="breadcrumb-item active">Edit Product</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <!-- left column -->
                    <div class="col-md-12">
                        <!-- general form elements -->
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        <div class="card card-primary">
                            <div class="card-header">
                                <h3 class="card-title">Edit Product</h3>
                            </div>
                            <!-- /.card-header -->
                            <!-- form start -->
                            <form method="post" action="{{route('admin.products.update', $product->id) }}" enctype="multipart/form-data">
                                @csrf
                                @method('PUT')
{{--                                <input value="{{$product->id}}" name="product_id" hidden>--}}
                                <div class="card-body">
                                    <div class="form-group">
                                        <label for="title">
                                            Title
                                        </label>
                                        <input type="text"
                                               class="form-control"
                                               id="title"
                                               name="title"
                                               placeholder="Enter Title"
                                               value="{{ $product->title }}"
                                               required
                                               >
                                    </div>

                                    <div class="form-group">
                                        <label for="description">
                                            Description
                                        </label>
                                        <textarea
                                               class="form-control"
                                               id="description"
                                               name="description"
                                               placeholder="Enter Description"
                                               required
                                               rows="10"
                                        >{{ $product->description }}</textarea>
                                      </div>
                                    <div class="form-group">
                                    <label for="inputStatus">Category</label>
                                        <select id="inputStatus" name="category_id" class="form-control custom-select">
                                           @foreach($categories as $category)
                                                <option value="{{ $category->id }}" {{ $product->category_id == $category->id ? 'selected': '' }}> {{ $category->name }} </option>
                                           @endforeach

                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <label for="image">
                                            Product's Photo
                                        </label>
                                        <div class="input-group">
                                            <img src="{{ $product->image_url }}" height="200">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="image">
                                            Change Image
                                        </label>
                                        <div class="input-group">
                                            <div class="custom-file">
                                                <input type="file"
                                                       class="custom-file-input"
                                                       id="image"
                                                       name="image"
                                                       >
                                                <label class="custom-file-label"
                                                       for="productImage">
                                                    Choose Another Image
                                                </label>
                                            </div>

                                            <div class="input-group-append">
                                                <span class="input-group-text">
                                                    change
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- /.card-body -->

                                <div class="card-footer">
                                    <button type="submit" class="btn btn-primary">Update</button>
                                </div>
                            </form>
                        </div>
                        <!-- /.card -->
                    </div>
                    <!--/.col (left) -->
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
@endsection

resources/views/admin/products/index.blade.php
@extends('admin.layouts.master')
@section('content')
    <div class="content-wrapper" style="min-height: 1299.69px;">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Products Table</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Home</a></li>
                            <li class="breadcrumb-item active">Products Table</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Products</h3>
                                <div class="card-tools">
                                    <ul class="pagination pagination-sm float-right">
                                        {{ $products->links('vendor.pagination.default') }}
                                    </ul>
                                </div>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body table-responsive p-0">
                                <table class="table table-hover text-nowrap">
                                    <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Title</th>
                                        <th>Description</th>
                                        <th>Price</th>
                                        <th>Category</th>
                                        <th>Last Updated at</th>
                                        <th>Show/Edit/Delete</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    @foreach($products as $product)
                                        <tr>
                                            <td>{{ $product->id }}</td>
                                            <td>{{ Str::limit($product->title, $limit = 30, $end = '...') }}</td>
                                            <td>{{ Str::limit($product->description, $limit = 50, $end = '...') }}</td>
                                            <td>{{ $product->price }}</td>
                                            <td>{{ $product->category->name }}</td>
                                            <td>{{ $product->updated_at }}</td>
                                            <td><a href="products/{{ $product->id }}" class="btn btn-info"><i class="fas fa-eye"></i></a>
                                                <a href="{{ route('admin.products.edit', $product->id) }}" class="btn btn-success"><i class="fas fa-edit"></i></a>
                                                <a href="{{ route('admin.products.destroy', $product->id) }}" class="btn btn-danger"
                                                   data-toggle="modal" data-target="#deleteModal{{$product->id}}"><i class="fas fa-trash"></i></a>
                                            </td>
                                        </tr>
                                        <div class="modal fade" id="deleteModal{{$product->id}}" tabindex="-1" role="dialog" aria-labelledby="Delete" aria-hidden="true">
                                          <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                              <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">Delete Product</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                  <span aria-hidden="true">&times;</span>
                                                </button>
                                              </div>
                                                <form action="{{ route('admin.products.destroy', $product->id) }}" method="post">
                                                  <div class="modal-body">
                                                    @csrf
                                                    @method('DELETE')
                                                    <h5 class="text-center">Are you sure you want to delete this Product?</h5>
                                                  </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                                        <button type="submit" class="btn btn-danger">Yes, Delete Product</button>
                                                    </div>
                                                </form>
                                              </div>
                                            </div>
                                          </div>
                                    @endforeach

                                    </tbody>
                                </table>
                            </div>
                            <!-- /.card-body -->

                            </div>

                        </div>
                        <!-- /.card -->
                    </div>
                </div>
                <!-- /.row -->
            </div>
        </section>
        <!-- /.content -->
    </div>

    <script>
        $('#staticBackdrop').modal(options)

        $(document).on('click','.delete',function(){
             let id = $(this).attr('data-id');
             $('#id').val(id);
        });
    </script>
@endsection

resources/views/admin/products/show.blade.php
@extends('admin.layouts.master')
@section('content')

<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1> Product Details </h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Home</a></li>
              <li class="breadcrumb-item"><a href="{{ route('admin.products.index') }}">Products</a></li>
              <li class="breadcrumb-item active">{{ Str::limit($product->title, $limit = 15, $end = '...') }}</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="card card-solid">
        <div class="card-body">
          <div class="row">
            <div class="col-12 col-sm-6">
              <h3 class="d-inline-block d-sm-none">{{ $product->title }}</h3>
              <div class="col-12">
                <img src="{{ $product->image_url }}" class="product-image" alt="Product Image">
              </div>
            </div>
            <div class="col-12 col-sm-6">
              <h3 class="my-3"><span style="color: #0c84ff">Name:</span> {{ $product->title }}</h3>
              <h5 class="my-3"><span style="color: #0c84ff">Category:</span> {{ $product->category->name }}</h5>
                <hr>
              <h5 class="my-3" style="color: #0c84ff">Description:</h5>
              <p> {{ $product->description }}</p>
            </div>
          </div>
        </div>
      </div>
      <!-- /.card -->

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
@endsection